[[repos]]
repo = "builtin"
hooks = [
  { id = "check-case-conflict" },
  { id = "check-merge-conflict" },
  { id = "end-of-file-fixer" },
  { id = "mixed-line-ending", args = ["--fix", "lf"] },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.7"
hooks = [
  { id = "ruff", args = ["--fix"] },
  { id = "ruff-format" },
]

[[repos]]
repo = "local"
hooks = [
  { id = "mypy", name = "mypy", entry = "python -m mypy", language = "system", types = ["python"], require_serial = true, exclude = "^(tests|tools)/" },
]

[[repos]]
repo = "https://github.com/pre-commit/mirrors-prettier"
rev = "v4.0.0-alpha.8"
hooks = [{ id = "prettier" }]

[[repos]]
repo = "https://github.com/doublify/pre-commit-rust"
rev = "v1.0"
hooks = [
  { id = "fmt" },
  { id = "cargo-check" },
  { id = "clippy" },
]

[[repos]]
repo = "local"
hooks = [
  { id = "doptest-legacy", name = "doptest legacy run", entry = "cargo run -r -p doptest -- legacy run", language = "system", pass_filenames = false, always_run = true },
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.41.0"
hooks = [{ id = "typos", args = ["--force-exclude"] }]
